package com.shana.house.mapper;

import com.shana.house.model.HouseImg;
import java.util.List;

public interface HouseImgMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_houseimg
     *
     * @mbg.generated Mon Nov 18 20:16:27 CST 2019
     */
    int deleteByPrimaryKey(Integer hiid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_houseimg
     *
     * @mbg.generated Mon Nov 18 20:16:27 CST 2019
     */
    int insert(HouseImg record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_houseimg
     *
     * @mbg.generated Mon Nov 18 20:16:27 CST 2019
     */
    HouseImg selectByPrimaryKey(Integer hiid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_houseimg
     *
     * @mbg.generated Mon Nov 18 20:16:27 CST 2019
     */
    List<HouseImg> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_houseimg
     *
     * @mbg.generated Mon Nov 18 20:16:27 CST 2019
     */
    int updateByPrimaryKey(HouseImg record);
}