package com.shana.house.mapper;

import com.shana.house.model.House;
import com.shana.house.qv.HouseQv;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;
import org.springframework.stereotype.Component;

import java.util.List;

@Component
@Mapper
public interface HouseMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_house
     *
     * @mbg.generated Mon Nov 18 20:16:27 CST 2019
     */
    int deleteByPrimaryKey(Integer hid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_house
     *
     * @mbg.generated Mon Nov 18 20:16:27 CST 2019
     */
    int insert(House record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_house
     *
     * @mbg.generated Mon Nov 18 20:16:27 CST 2019
     */
    House selectByPrimaryKey(Integer hid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_house
     *
     * @mbg.generated Mon Nov 18 20:16:27 CST 2019
     */
    List<House> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_house
     *
     * @mbg.generated Mon Nov 18 20:16:27 CST 2019
     */
    int updateByPrimaryKey(House record);

    HouseQv selectHouseQvByHid(Integer hid);

    void insertHnameAndDes(House house);

    List<House> selectAllHouseByCity(String city);

    @Update("update t_house set housetype=#{housetype},rentaltype=#{rentaltype},maxtenant=#{maxtenant},bedroomnum=#{bedroomnum}," +
            "bednum=#{bednum},bathroomnum=#{bathroomnum},location=#{location},city=#{city} where hid=#{hid}")
    void updateHouseMessage(House house);

    @Update("update t_house set price=#{price},startdate=#{startdate},enddate=#{enddate} where hid=#{hid}")
    void updateHousePriceAndDate(House house);

    @Select("select * from t_house where uid=#{uid}")
    List<House> selectHouseByUid(String uid);
}