package com.shana.house.mapper;

import com.shana.house.model.House;
import com.shana.house.model.HouseInstallations;
import com.shana.house.qv.HouseQv;
import org.apache.ibatis.annotations.Mapper;
import org.springframework.stereotype.Component;

import org.apache.ibatis.annotations.Mapper;
import org.springframework.stereotype.Component;

import java.util.List;

@Component
@Mapper
public interface HouseMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_house
     *
     * @mbg.generated Mon Nov 18 20:16:27 CST 2019
     */
    int deleteByPrimaryKey(Integer hid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_house
     *
     * @mbg.generated Mon Nov 18 20:16:27 CST 2019
     */
    int insert(House record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_house
     *
     * @mbg.generated Mon Nov 18 20:16:27 CST 2019
     */
    House selectByPrimaryKey(Integer hid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_house
     *
     * @mbg.generated Mon Nov 18 20:16:27 CST 2019
     */
    List<House> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_house
     *
     * @mbg.generated Mon Nov 18 20:16:27 CST 2019
     */
    int updateByPrimaryKey(House record);

    HouseQv selectHouseQvByHid(Integer hid);

    void insertHnameAndDes(House house);

    List<House> selectAllHouseByCity(String city);

}