package com.shana.house.mapper;

import com.shana.house.model.HouseInstallations;
import org.apache.ibatis.annotations.Mapper;
import org.springframework.stereotype.Component;

import java.util.List;

@Mapper
@Component
public interface HouseInstallationsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_houseinstallations
     *
     * @mbg.generated Mon Nov 18 20:16:27 CST 2019
     */
    int deleteByPrimaryKey(Integer hsid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_houseinstallations
     *
     * @mbg.generated Mon Nov 18 20:16:27 CST 2019
     */
    int insert(HouseInstallations record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_houseinstallations
     *
     * @mbg.generated Mon Nov 18 20:16:27 CST 2019
     */
    HouseInstallations selectByPrimaryKey(Integer hsid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_houseinstallations
     *
     * @mbg.generated Mon Nov 18 20:16:27 CST 2019
     */
    List<HouseInstallations> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_houseinstallations
     *
     * @mbg.generated Mon Nov 18 20:16:27 CST 2019
     */
    int updateByPrimaryKey(HouseInstallations record);


    HouseInstallations selectOneHouseInstallations(int hid);

}