package com.shana.house.mapper;

import com.shana.house.model.HouseStars;
import java.util.List;

public interface HouseStarsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_housestars
     *
     * @mbg.generated Mon Nov 18 20:16:27 CST 2019
     */
    int deleteByPrimaryKey(Integer hsid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_housestars
     *
     * @mbg.generated Mon Nov 18 20:16:27 CST 2019
     */
    int insert(HouseStars record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_housestars
     *
     * @mbg.generated Mon Nov 18 20:16:27 CST 2019
     */
    HouseStars selectByPrimaryKey(Integer hsid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_housestars
     *
     * @mbg.generated Mon Nov 18 20:16:27 CST 2019
     */
    List<HouseStars> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_housestars
     *
     * @mbg.generated Mon Nov 18 20:16:27 CST 2019
     */
    int updateByPrimaryKey(HouseStars record);
}