package com.shana.house.mapper;

import com.shana.house.model.HouseImg;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Select;
import org.springframework.stereotype.Component;

import java.util.List;

@Mapper
@Component
public interface HouseImgMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_houseimg
     *
     * @mbg.generated Mon Nov 18 20:16:27 CST 2019
     */
    int deleteByPrimaryKey(Integer hiid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_houseimg
     *
     * @mbg.generated Mon Nov 18 20:16:27 CST 2019
     */
    int insert(HouseImg record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_houseimg
     *
     * @mbg.generated Mon Nov 18 20:16:27 CST 2019
     */
    HouseImg selectByPrimaryKey(Integer hiid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_houseimg
     *
     * @mbg.generated Mon Nov 18 20:16:27 CST 2019
     */
    List<HouseImg> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_houseimg
     *
     * @mbg.generated Mon Nov 18 20:16:27 CST 2019
     */
    int updateByPrimaryKey(HouseImg record);

    @Insert("insert into t_houseimg(hid,img) values(#{hid},#{img})")
    void insertImg(HouseImg houseImg);

    @Select("select * from t_houseimg where hid=#{hid}")
    List<HouseImg> selectAllImgByHid(int hid);

    @Delete("delete from t_houseimg where hid=#{hid}")
    void deleteByHid(int hid);
}