server:
  port: 8081
logging:
  level:
    com:
      looedu:
        mapper: debug
mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml        # mybatis配置文件所在路径
  type-aliases-package:
    com.shana.house             # 所有Entity别名类所在包

  mapper-locations:
    - classpath:mybatis/mapper/**/*.xml                       # mapper映射文件
spring:
  application:
    name: house-producer-8081
  datasource:
    url: jdbc:mysql://116.62.218.239:3306/house?characterEncoding=UTF-8
    username: root
    password: admin
    dbcp2:
      min-idle: 5                                        # 数据库连接池的最小维持连接数
      initial-size: 5                                       # 初始化连接数
      max-total: 5                                          # 最大连接数
      max-wait-millis: 200                                 # 等待连接获取的最大超时时间
  servlet:
    multipart:
      max-file-size: 50MB # 限制文件上传的大小
  jackson:
    #参数意义：
    #JsonInclude.Include.ALWAYS       默认
    #JsonInclude.Include.NON_DEFAULT   属性为默认值不序列化
    #JsonInclude.Include.NON_EMPTY     属性为 空（””） 或者为 NULL 都不序列化
    #JsonInclude.Include.NON_NULL      属性为NULL  不序列化
    default-property-inclusion: ALWAYS
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  redis:
    #地址
    host: 116.62.218.239
    #端口
    port: 6379
    #索引库
    database: 1
    #密码
    password:
    #超时时间
    timeout: 5000ms
  session:
    store-type: redis

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10001/eureka
  instance:
    lease-renewal-interval-in-seconds: 5 # 每隔5秒发送一次心跳
    lease-expiration-duration-in-seconds: 10 # 10秒不发送就过期
    prefer-ip-address: true
    ip-address: 127.0.0.1
    instance-id: ${spring.application.name}:${server.port}
fdfs:
  so-timeout: 1501 #超时时间
  connect-timeout: 601  #连接超时时间
  thumb-image: # 缩略图
    width: 60
    height: 60
  tracker-list: # tracker地址
    - 116.62.218.239:22122