server:
  port: 8081
mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml        # mybatis配置文件所在路径
  type-aliases-package:
    com.shana.house             # 所有Entity别名类所在包

  mapper-locations:
    - classpath:mybatis/mapper/**/*.xml                       # mapper映射文件
spring:
  application:
    name: house-producer-8081
  datasource:
    url: jdbc:mysql://116.62.218.239:3306/house?characterEncoding=UTF-8
    username: root
    password: admin
    dbcp2:
      min-idle: 5                                        # 数据库连接池的最小维持连接数
      initial-size: 5                                       # 初始化连接数
      max-total: 5                                          # 最大连接数
      max-wait-millis: 200                                 # 等待连接获取的最大超时时间
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10001/eureka
  instance:
    lease-renewal-interval-in-seconds: 5 # 每隔5秒发送一次心跳
    lease-expiration-duration-in-seconds: 10 # 10秒不发送就过期
    prefer-ip-address: true
    ip-address: 127.0.0.1
    instance-id: ${spring.application.name}:${server.port}