package com.shana.house.qv;

import lombok.Data;

import java.util.Date;
@Data
public class UserP {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.uid
     *
     * @mbg.generated Mon Nov 18 20:16:27 CST 2019
     */
    private Integer uid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.account
     *
     * @mbg.generated Mon Nov 18 20:16:27 CST 2019
     */
    private String account;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.password
     *
     * @mbg.generated Mon Nov 18 20:16:27 CST 2019
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.sex
     *
     * @mbg.generated Mon Nov 18 20:16:27 CST 2019
     */
    private String sex;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.birthday
     *
     * @mbg.generated Mon Nov 18 20:16:27 CST 2019
     */
    private Date birthday;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.age
     *
     * @mbg.generated Mon Nov 18 20:16:27 CST 2019
     */
    private Integer age;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.email
     *
     * @mbg.generated Mon Nov 18 20:16:27 CST 2019
     */
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.mobilephone
     *
     * @mbg.generated Mon Nov 18 20:16:27 CST 2019
     */
    private String mobilephone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.selfintroduction
     *
     * @mbg.generated Mon Nov 18 20:16:27 CST 2019
     */
    private String selfintroduction;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.headimg
     *
     * @mbg.generated Mon Nov 18 20:16:27 CST 2019
     */
    private String headimg;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.idcard
     *
     * @mbg.generated Mon Nov 18 20:16:27 CST 2019
     */
    private String idcard;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.createdate
     *
     * @mbg.generated Mon Nov 18 20:16:27 CST 2019
     */
    private Date createdate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.status
     *
     * @mbg.generated Mon Nov 18 20:16:27 CST 2019
     */
    private Integer status;

    private String phonecode;
}
