package com.shana.house.model;

import java.util.Date;

public class HouseBed {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_housebed.hbid
     *
     * @mbg.generated Mon Nov 18 20:16:27 CST 2019
     */
    private Integer hbid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_housebed.hid
     *
     * @mbg.generated Mon Nov 18 20:16:27 CST 2019
     */
    private Integer hid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_housebed.bedroomname
     *
     * @mbg.generated Mon Nov 18 20:16:27 CST 2019
     */
    private String bedroomname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_housebed.bedtype
     *
     * @mbg.generated Mon Nov 18 20:16:27 CST 2019
     */
    private Integer bedtype;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_housebed.bedcount
     *
     * @mbg.generated Mon Nov 18 20:16:27 CST 2019
     */
    private Integer bedcount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_housebed.createdate
     *
     * @mbg.generated Mon Nov 18 20:16:27 CST 2019
     */
    private Date createdate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_housebed.status
     *
     * @mbg.generated Mon Nov 18 20:16:27 CST 2019
     */
    private Integer status;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_housebed.hbid
     *
     * @return the value of t_housebed.hbid
     *
     * @mbg.generated Mon Nov 18 20:16:27 CST 2019
     */
    public Integer getHbid() {
        return hbid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_housebed.hbid
     *
     * @param hbid the value for t_housebed.hbid
     *
     * @mbg.generated Mon Nov 18 20:16:27 CST 2019
     */
    public void setHbid(Integer hbid) {
        this.hbid = hbid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_housebed.hid
     *
     * @return the value of t_housebed.hid
     *
     * @mbg.generated Mon Nov 18 20:16:27 CST 2019
     */
    public Integer getHid() {
        return hid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_housebed.hid
     *
     * @param hid the value for t_housebed.hid
     *
     * @mbg.generated Mon Nov 18 20:16:27 CST 2019
     */
    public void setHid(Integer hid) {
        this.hid = hid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_housebed.bedroomname
     *
     * @return the value of t_housebed.bedroomname
     *
     * @mbg.generated Mon Nov 18 20:16:27 CST 2019
     */
    public String getBedroomname() {
        return bedroomname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_housebed.bedroomname
     *
     * @param bedroomname the value for t_housebed.bedroomname
     *
     * @mbg.generated Mon Nov 18 20:16:27 CST 2019
     */
    public void setBedroomname(String bedroomname) {
        this.bedroomname = bedroomname == null ? null : bedroomname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_housebed.bedtype
     *
     * @return the value of t_housebed.bedtype
     *
     * @mbg.generated Mon Nov 18 20:16:27 CST 2019
     */
    public Integer getBedtype() {
        return bedtype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_housebed.bedtype
     *
     * @param bedtype the value for t_housebed.bedtype
     *
     * @mbg.generated Mon Nov 18 20:16:27 CST 2019
     */
    public void setBedtype(Integer bedtype) {
        this.bedtype = bedtype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_housebed.bedcount
     *
     * @return the value of t_housebed.bedcount
     *
     * @mbg.generated Mon Nov 18 20:16:27 CST 2019
     */
    public Integer getBedcount() {
        return bedcount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_housebed.bedcount
     *
     * @param bedcount the value for t_housebed.bedcount
     *
     * @mbg.generated Mon Nov 18 20:16:27 CST 2019
     */
    public void setBedcount(Integer bedcount) {
        this.bedcount = bedcount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_housebed.createdate
     *
     * @return the value of t_housebed.createdate
     *
     * @mbg.generated Mon Nov 18 20:16:27 CST 2019
     */
    public Date getCreatedate() {
        return createdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_housebed.createdate
     *
     * @param createdate the value for t_housebed.createdate
     *
     * @mbg.generated Mon Nov 18 20:16:27 CST 2019
     */
    public void setCreatedate(Date createdate) {
        this.createdate = createdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_housebed.status
     *
     * @return the value of t_housebed.status
     *
     * @mbg.generated Mon Nov 18 20:16:27 CST 2019
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_housebed.status
     *
     * @param status the value for t_housebed.status
     *
     * @mbg.generated Mon Nov 18 20:16:27 CST 2019
     */
    public void setStatus(Integer status) {
        this.status = status;
    }
}