package com.shana.house.model;

import java.util.Date;

public class HouseInstallations {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_houseinstallations.hsid
     *
     * @mbg.generated Mon Nov 18 20:16:27 CST 2019
     */
    private Integer hsid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_houseinstallations.hid
     *
     * @mbg.generated Mon Nov 18 20:16:27 CST 2019
     */
    private Integer hid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_houseinstallations.needed
     *
     * @mbg.generated Mon Nov 18 20:16:27 CST 2019
     */
    private Integer needed;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_houseinstallations.airconditioner
     *
     * @mbg.generated Mon Nov 18 20:16:27 CST 2019
     */
    private Integer airconditioner;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_houseinstallations.heating
     *
     * @mbg.generated Mon Nov 18 20:16:27 CST 2019
     */
    private Integer heating;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_houseinstallations.hairdrier
     *
     * @mbg.generated Mon Nov 18 20:16:27 CST 2019
     */
    private Integer hairdrier;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_houseinstallations.iron
     *
     * @mbg.generated Mon Nov 18 20:16:27 CST 2019
     */
    private Integer iron;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_houseinstallations.television
     *
     * @mbg.generated Mon Nov 18 20:16:27 CST 2019
     */
    private Integer television;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_houseinstallations.independententry
     *
     * @mbg.generated Mon Nov 18 20:16:27 CST 2019
     */
    private Integer independententry;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_houseinstallations.shampoo
     *
     * @mbg.generated Mon Nov 18 20:16:27 CST 2019
     */
    private Integer shampoo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_houseinstallations.wifi
     *
     * @mbg.generated Mon Nov 18 20:16:27 CST 2019
     */
    private Integer wifi;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_houseinstallations.desk
     *
     * @mbg.generated Mon Nov 18 20:16:27 CST 2019
     */
    private Integer desk;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_houseinstallations.breakfast
     *
     * @mbg.generated Mon Nov 18 20:16:27 CST 2019
     */
    private Integer breakfast;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_houseinstallations.fireextinguisher
     *
     * @mbg.generated Mon Nov 18 20:16:27 CST 2019
     */
    private Integer fireextinguisher;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_houseinstallations.coalarm
     *
     * @mbg.generated Mon Nov 18 20:16:27 CST 2019
     */
    private Integer coalarm;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_houseinstallations.smokedetector
     *
     * @mbg.generated Mon Nov 18 20:16:27 CST 2019
     */
    private Integer smokedetector;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_houseinstallations.firstaidkit
     *
     * @mbg.generated Mon Nov 18 20:16:27 CST 2019
     */
    private Integer firstaidkit;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_houseinstallations.kitchen
     *
     * @mbg.generated Mon Nov 18 20:16:27 CST 2019
     */
    private Integer kitchen;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_houseinstallations.washingmachine
     *
     * @mbg.generated Mon Nov 18 20:16:27 CST 2019
     */
    private Integer washingmachine;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_houseinstallations.dryer
     *
     * @mbg.generated Mon Nov 18 20:16:27 CST 2019
     */
    private Integer dryer;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_houseinstallations.parkingspace
     *
     * @mbg.generated Mon Nov 18 20:16:27 CST 2019
     */
    private Integer parkingspace;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_houseinstallations.gym
     *
     * @mbg.generated Mon Nov 18 20:16:27 CST 2019
     */
    private Integer gym;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_houseinstallations.swimmingpool
     *
     * @mbg.generated Mon Nov 18 20:16:27 CST 2019
     */
    private Integer swimmingpool;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_houseinstallations.bathtub
     *
     * @mbg.generated Mon Nov 18 20:16:27 CST 2019
     */
    private Integer bathtub;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_houseinstallations.elevator
     *
     * @mbg.generated Mon Nov 18 20:16:27 CST 2019
     */
    private Integer elevator;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_houseinstallations.createdate
     *
     * @mbg.generated Mon Nov 18 20:16:27 CST 2019
     */
    private Date createdate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_houseinstallations.status
     *
     * @mbg.generated Mon Nov 18 20:16:27 CST 2019
     */
    private Integer status;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_houseinstallations.hsid
     *
     * @return the value of t_houseinstallations.hsid
     *
     * @mbg.generated Mon Nov 18 20:16:27 CST 2019
     */
    public Integer getHsid() {
        return hsid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_houseinstallations.hsid
     *
     * @param hsid the value for t_houseinstallations.hsid
     *
     * @mbg.generated Mon Nov 18 20:16:27 CST 2019
     */
    public void setHsid(Integer hsid) {
        this.hsid = hsid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_houseinstallations.hid
     *
     * @return the value of t_houseinstallations.hid
     *
     * @mbg.generated Mon Nov 18 20:16:27 CST 2019
     */
    public Integer getHid() {
        return hid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_houseinstallations.hid
     *
     * @param hid the value for t_houseinstallations.hid
     *
     * @mbg.generated Mon Nov 18 20:16:27 CST 2019
     */
    public void setHid(Integer hid) {
        this.hid = hid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_houseinstallations.needed
     *
     * @return the value of t_houseinstallations.needed
     *
     * @mbg.generated Mon Nov 18 20:16:27 CST 2019
     */
    public Integer getNeeded() {
        return needed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_houseinstallations.needed
     *
     * @param needed the value for t_houseinstallations.needed
     *
     * @mbg.generated Mon Nov 18 20:16:27 CST 2019
     */
    public void setNeeded(Integer needed) {
        this.needed = needed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_houseinstallations.airconditioner
     *
     * @return the value of t_houseinstallations.airconditioner
     *
     * @mbg.generated Mon Nov 18 20:16:27 CST 2019
     */
    public Integer getAirconditioner() {
        return airconditioner;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_houseinstallations.airconditioner
     *
     * @param airconditioner the value for t_houseinstallations.airconditioner
     *
     * @mbg.generated Mon Nov 18 20:16:27 CST 2019
     */
    public void setAirconditioner(Integer airconditioner) {
        this.airconditioner = airconditioner;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_houseinstallations.heating
     *
     * @return the value of t_houseinstallations.heating
     *
     * @mbg.generated Mon Nov 18 20:16:27 CST 2019
     */
    public Integer getHeating() {
        return heating;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_houseinstallations.heating
     *
     * @param heating the value for t_houseinstallations.heating
     *
     * @mbg.generated Mon Nov 18 20:16:27 CST 2019
     */
    public void setHeating(Integer heating) {
        this.heating = heating;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_houseinstallations.hairdrier
     *
     * @return the value of t_houseinstallations.hairdrier
     *
     * @mbg.generated Mon Nov 18 20:16:27 CST 2019
     */
    public Integer getHairdrier() {
        return hairdrier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_houseinstallations.hairdrier
     *
     * @param hairdrier the value for t_houseinstallations.hairdrier
     *
     * @mbg.generated Mon Nov 18 20:16:27 CST 2019
     */
    public void setHairdrier(Integer hairdrier) {
        this.hairdrier = hairdrier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_houseinstallations.iron
     *
     * @return the value of t_houseinstallations.iron
     *
     * @mbg.generated Mon Nov 18 20:16:27 CST 2019
     */
    public Integer getIron() {
        return iron;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_houseinstallations.iron
     *
     * @param iron the value for t_houseinstallations.iron
     *
     * @mbg.generated Mon Nov 18 20:16:27 CST 2019
     */
    public void setIron(Integer iron) {
        this.iron = iron;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_houseinstallations.television
     *
     * @return the value of t_houseinstallations.television
     *
     * @mbg.generated Mon Nov 18 20:16:27 CST 2019
     */
    public Integer getTelevision() {
        return television;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_houseinstallations.television
     *
     * @param television the value for t_houseinstallations.television
     *
     * @mbg.generated Mon Nov 18 20:16:27 CST 2019
     */
    public void setTelevision(Integer television) {
        this.television = television;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_houseinstallations.independententry
     *
     * @return the value of t_houseinstallations.independententry
     *
     * @mbg.generated Mon Nov 18 20:16:27 CST 2019
     */
    public Integer getIndependententry() {
        return independententry;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_houseinstallations.independententry
     *
     * @param independententry the value for t_houseinstallations.independententry
     *
     * @mbg.generated Mon Nov 18 20:16:27 CST 2019
     */
    public void setIndependententry(Integer independententry) {
        this.independententry = independententry;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_houseinstallations.shampoo
     *
     * @return the value of t_houseinstallations.shampoo
     *
     * @mbg.generated Mon Nov 18 20:16:27 CST 2019
     */
    public Integer getShampoo() {
        return shampoo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_houseinstallations.shampoo
     *
     * @param shampoo the value for t_houseinstallations.shampoo
     *
     * @mbg.generated Mon Nov 18 20:16:27 CST 2019
     */
    public void setShampoo(Integer shampoo) {
        this.shampoo = shampoo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_houseinstallations.wifi
     *
     * @return the value of t_houseinstallations.wifi
     *
     * @mbg.generated Mon Nov 18 20:16:27 CST 2019
     */
    public Integer getWifi() {
        return wifi;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_houseinstallations.wifi
     *
     * @param wifi the value for t_houseinstallations.wifi
     *
     * @mbg.generated Mon Nov 18 20:16:27 CST 2019
     */
    public void setWifi(Integer wifi) {
        this.wifi = wifi;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_houseinstallations.desk
     *
     * @return the value of t_houseinstallations.desk
     *
     * @mbg.generated Mon Nov 18 20:16:27 CST 2019
     */
    public Integer getDesk() {
        return desk;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_houseinstallations.desk
     *
     * @param desk the value for t_houseinstallations.desk
     *
     * @mbg.generated Mon Nov 18 20:16:27 CST 2019
     */
    public void setDesk(Integer desk) {
        this.desk = desk;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_houseinstallations.breakfast
     *
     * @return the value of t_houseinstallations.breakfast
     *
     * @mbg.generated Mon Nov 18 20:16:27 CST 2019
     */
    public Integer getBreakfast() {
        return breakfast;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_houseinstallations.breakfast
     *
     * @param breakfast the value for t_houseinstallations.breakfast
     *
     * @mbg.generated Mon Nov 18 20:16:27 CST 2019
     */
    public void setBreakfast(Integer breakfast) {
        this.breakfast = breakfast;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_houseinstallations.fireextinguisher
     *
     * @return the value of t_houseinstallations.fireextinguisher
     *
     * @mbg.generated Mon Nov 18 20:16:27 CST 2019
     */
    public Integer getFireextinguisher() {
        return fireextinguisher;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_houseinstallations.fireextinguisher
     *
     * @param fireextinguisher the value for t_houseinstallations.fireextinguisher
     *
     * @mbg.generated Mon Nov 18 20:16:27 CST 2019
     */
    public void setFireextinguisher(Integer fireextinguisher) {
        this.fireextinguisher = fireextinguisher;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_houseinstallations.coalarm
     *
     * @return the value of t_houseinstallations.coalarm
     *
     * @mbg.generated Mon Nov 18 20:16:27 CST 2019
     */
    public Integer getCoalarm() {
        return coalarm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_houseinstallations.coalarm
     *
     * @param coalarm the value for t_houseinstallations.coalarm
     *
     * @mbg.generated Mon Nov 18 20:16:27 CST 2019
     */
    public void setCoalarm(Integer coalarm) {
        this.coalarm = coalarm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_houseinstallations.smokedetector
     *
     * @return the value of t_houseinstallations.smokedetector
     *
     * @mbg.generated Mon Nov 18 20:16:27 CST 2019
     */
    public Integer getSmokedetector() {
        return smokedetector;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_houseinstallations.smokedetector
     *
     * @param smokedetector the value for t_houseinstallations.smokedetector
     *
     * @mbg.generated Mon Nov 18 20:16:27 CST 2019
     */
    public void setSmokedetector(Integer smokedetector) {
        this.smokedetector = smokedetector;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_houseinstallations.firstaidkit
     *
     * @return the value of t_houseinstallations.firstaidkit
     *
     * @mbg.generated Mon Nov 18 20:16:27 CST 2019
     */
    public Integer getFirstaidkit() {
        return firstaidkit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_houseinstallations.firstaidkit
     *
     * @param firstaidkit the value for t_houseinstallations.firstaidkit
     *
     * @mbg.generated Mon Nov 18 20:16:27 CST 2019
     */
    public void setFirstaidkit(Integer firstaidkit) {
        this.firstaidkit = firstaidkit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_houseinstallations.kitchen
     *
     * @return the value of t_houseinstallations.kitchen
     *
     * @mbg.generated Mon Nov 18 20:16:27 CST 2019
     */
    public Integer getKitchen() {
        return kitchen;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_houseinstallations.kitchen
     *
     * @param kitchen the value for t_houseinstallations.kitchen
     *
     * @mbg.generated Mon Nov 18 20:16:27 CST 2019
     */
    public void setKitchen(Integer kitchen) {
        this.kitchen = kitchen;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_houseinstallations.washingmachine
     *
     * @return the value of t_houseinstallations.washingmachine
     *
     * @mbg.generated Mon Nov 18 20:16:27 CST 2019
     */
    public Integer getWashingmachine() {
        return washingmachine;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_houseinstallations.washingmachine
     *
     * @param washingmachine the value for t_houseinstallations.washingmachine
     *
     * @mbg.generated Mon Nov 18 20:16:27 CST 2019
     */
    public void setWashingmachine(Integer washingmachine) {
        this.washingmachine = washingmachine;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_houseinstallations.dryer
     *
     * @return the value of t_houseinstallations.dryer
     *
     * @mbg.generated Mon Nov 18 20:16:27 CST 2019
     */
    public Integer getDryer() {
        return dryer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_houseinstallations.dryer
     *
     * @param dryer the value for t_houseinstallations.dryer
     *
     * @mbg.generated Mon Nov 18 20:16:27 CST 2019
     */
    public void setDryer(Integer dryer) {
        this.dryer = dryer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_houseinstallations.parkingspace
     *
     * @return the value of t_houseinstallations.parkingspace
     *
     * @mbg.generated Mon Nov 18 20:16:27 CST 2019
     */
    public Integer getParkingspace() {
        return parkingspace;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_houseinstallations.parkingspace
     *
     * @param parkingspace the value for t_houseinstallations.parkingspace
     *
     * @mbg.generated Mon Nov 18 20:16:27 CST 2019
     */
    public void setParkingspace(Integer parkingspace) {
        this.parkingspace = parkingspace;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_houseinstallations.gym
     *
     * @return the value of t_houseinstallations.gym
     *
     * @mbg.generated Mon Nov 18 20:16:27 CST 2019
     */
    public Integer getGym() {
        return gym;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_houseinstallations.gym
     *
     * @param gym the value for t_houseinstallations.gym
     *
     * @mbg.generated Mon Nov 18 20:16:27 CST 2019
     */
    public void setGym(Integer gym) {
        this.gym = gym;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_houseinstallations.swimmingpool
     *
     * @return the value of t_houseinstallations.swimmingpool
     *
     * @mbg.generated Mon Nov 18 20:16:27 CST 2019
     */
    public Integer getSwimmingpool() {
        return swimmingpool;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_houseinstallations.swimmingpool
     *
     * @param swimmingpool the value for t_houseinstallations.swimmingpool
     *
     * @mbg.generated Mon Nov 18 20:16:27 CST 2019
     */
    public void setSwimmingpool(Integer swimmingpool) {
        this.swimmingpool = swimmingpool;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_houseinstallations.bathtub
     *
     * @return the value of t_houseinstallations.bathtub
     *
     * @mbg.generated Mon Nov 18 20:16:27 CST 2019
     */
    public Integer getBathtub() {
        return bathtub;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_houseinstallations.bathtub
     *
     * @param bathtub the value for t_houseinstallations.bathtub
     *
     * @mbg.generated Mon Nov 18 20:16:27 CST 2019
     */
    public void setBathtub(Integer bathtub) {
        this.bathtub = bathtub;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_houseinstallations.elevator
     *
     * @return the value of t_houseinstallations.elevator
     *
     * @mbg.generated Mon Nov 18 20:16:27 CST 2019
     */
    public Integer getElevator() {
        return elevator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_houseinstallations.elevator
     *
     * @param elevator the value for t_houseinstallations.elevator
     *
     * @mbg.generated Mon Nov 18 20:16:27 CST 2019
     */
    public void setElevator(Integer elevator) {
        this.elevator = elevator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_houseinstallations.createdate
     *
     * @return the value of t_houseinstallations.createdate
     *
     * @mbg.generated Mon Nov 18 20:16:27 CST 2019
     */
    public Date getCreatedate() {
        return createdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_houseinstallations.createdate
     *
     * @param createdate the value for t_houseinstallations.createdate
     *
     * @mbg.generated Mon Nov 18 20:16:27 CST 2019
     */
    public void setCreatedate(Date createdate) {
        this.createdate = createdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_houseinstallations.status
     *
     * @return the value of t_houseinstallations.status
     *
     * @mbg.generated Mon Nov 18 20:16:27 CST 2019
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_houseinstallations.status
     *
     * @param status the value for t_houseinstallations.status
     *
     * @mbg.generated Mon Nov 18 20:16:27 CST 2019
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    @Override
    public String toString() {
        return "HouseInstallations{" +
                "hsid=" + hsid +
                ", hid=" + hid +
                ", needed=" + needed +
                ", airconditioner=" + airconditioner +
                ", heating=" + heating +
                ", hairdrier=" + hairdrier +
                ", iron=" + iron +
                ", television=" + television +
                ", independententry=" + independententry +
                ", shampoo=" + shampoo +
                ", wifi=" + wifi +
                ", desk=" + desk +
                ", breakfast=" + breakfast +
                ", fireextinguisher=" + fireextinguisher +
                ", coalarm=" + coalarm +
                ", smokedetector=" + smokedetector +
                ", firstaidkit=" + firstaidkit +
                ", kitchen=" + kitchen +
                ", washingmachine=" + washingmachine +
                ", dryer=" + dryer +
                ", parkingspace=" + parkingspace +
                ", gym=" + gym +
                ", swimmingpool=" + swimmingpool +
                ", bathtub=" + bathtub +
                ", elevator=" + elevator +
                ", createdate=" + createdate +
                ", status=" + status +
                '}';
    }
}