package com.shana.house.model;

import java.util.Date;

public class HouseComment {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_housecomment.hcid
     *
     * @mbg.generated Mon Nov 18 20:16:27 CST 2019
     */
    private Integer hcid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_housecomment.hid
     *
     * @mbg.generated Mon Nov 18 20:16:27 CST 2019
     */
    private Integer hid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_housecomment.uid
     *
     * @mbg.generated Mon Nov 18 20:16:27 CST 2019
     */
    private Integer uid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_housecomment.message
     *
     * @mbg.generated Mon Nov 18 20:16:27 CST 2019
     */
    private String message;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_housecomment.createdate
     *
     * @mbg.generated Mon Nov 18 20:16:27 CST 2019
     */

    private Date createdate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_housecomment.status
     *
     * @mbg.generated Mon Nov 18 20:16:27 CST 2019
     */
    private Integer status;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_housecomment.hcid
     *
     * @return the value of t_housecomment.hcid
     *
     * @mbg.generated Mon Nov 18 20:16:27 CST 2019
     */
    public Integer getHcid() {
        return hcid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_housecomment.hcid
     *
     * @param hcid the value for t_housecomment.hcid
     *
     * @mbg.generated Mon Nov 18 20:16:27 CST 2019
     */
    public void setHcid(Integer hcid) {
        this.hcid = hcid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_housecomment.hid
     *
     * @return the value of t_housecomment.hid
     *
     * @mbg.generated Mon Nov 18 20:16:27 CST 2019
     */
    public Integer getHid() {
        return hid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_housecomment.hid
     *
     * @param hid the value for t_housecomment.hid
     *
     * @mbg.generated Mon Nov 18 20:16:27 CST 2019
     */
    public void setHid(Integer hid) {
        this.hid = hid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_housecomment.uid
     *
     * @return the value of t_housecomment.uid
     *
     * @mbg.generated Mon Nov 18 20:16:27 CST 2019
     */
    public Integer getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_housecomment.uid
     *
     * @param uid the value for t_housecomment.uid
     *
     * @mbg.generated Mon Nov 18 20:16:27 CST 2019
     */
    public void setUid(Integer uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_housecomment.message
     *
     * @return the value of t_housecomment.message
     *
     * @mbg.generated Mon Nov 18 20:16:27 CST 2019
     */
    public String getMessage() {
        return message;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_housecomment.message
     *
     * @param message the value for t_housecomment.message
     *
     * @mbg.generated Mon Nov 18 20:16:27 CST 2019
     */
    public void setMessage(String message) {
        this.message = message == null ? null : message.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_housecomment.createdate
     *
     * @return the value of t_housecomment.createdate
     *
     * @mbg.generated Mon Nov 18 20:16:27 CST 2019
     */
    public Date getCreatedate() {
        return createdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_housecomment.createdate
     *
     * @param createdate the value for t_housecomment.createdate
     *
     * @mbg.generated Mon Nov 18 20:16:27 CST 2019
     */
    public void setCreatedate(Date createdate) {
        this.createdate = createdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_housecomment.status
     *
     * @return the value of t_housecomment.status
     *
     * @mbg.generated Mon Nov 18 20:16:27 CST 2019
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_housecomment.status
     *
     * @param status the value for t_housecomment.status
     *
     * @mbg.generated Mon Nov 18 20:16:27 CST 2019
     */
    public void setStatus(Integer status) {
        this.status = status;
    }
}