package com.shana.house.model;

import java.util.Date;

public class HouseStars {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_housestars.hsid
     *
     * @mbg.generated Mon Nov 18 20:16:27 CST 2019
     */
    private Integer hsid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_housestars.hid
     *
     * @mbg.generated Mon Nov 18 20:16:27 CST 2019
     */
    private Integer hid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_housestars.described
     *
     * @mbg.generated Mon Nov 18 20:16:27 CST 2019
     */
    private Double described;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_housestars.location
     *
     * @mbg.generated Mon Nov 18 20:16:27 CST 2019
     */
    private Double location;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_housestars.communication
     *
     * @mbg.generated Mon Nov 18 20:16:27 CST 2019
     */
    private Double communication;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_housestars.occupancy
     *
     * @mbg.generated Mon Nov 18 20:16:27 CST 2019
     */
    private Double occupancy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_housestars.clean
     *
     * @mbg.generated Mon Nov 18 20:16:27 CST 2019
     */
    private Double clean;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_housestars.costperformance
     *
     * @mbg.generated Mon Nov 18 20:16:27 CST 2019
     */
    private Double costperformance;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_housestars.createdate
     *
     * @mbg.generated Mon Nov 18 20:16:27 CST 2019
     */
    private Date createdate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_housestars.status
     *
     * @mbg.generated Mon Nov 18 20:16:27 CST 2019
     */
    private Integer status;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_housestars.hsid
     *
     * @return the value of t_housestars.hsid
     *
     * @mbg.generated Mon Nov 18 20:16:27 CST 2019
     */
    public Integer getHsid() {
        return hsid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_housestars.hsid
     *
     * @param hsid the value for t_housestars.hsid
     *
     * @mbg.generated Mon Nov 18 20:16:27 CST 2019
     */
    public void setHsid(Integer hsid) {
        this.hsid = hsid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_housestars.hid
     *
     * @return the value of t_housestars.hid
     *
     * @mbg.generated Mon Nov 18 20:16:27 CST 2019
     */
    public Integer getHid() {
        return hid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_housestars.hid
     *
     * @param hid the value for t_housestars.hid
     *
     * @mbg.generated Mon Nov 18 20:16:27 CST 2019
     */
    public void setHid(Integer hid) {
        this.hid = hid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_housestars.described
     *
     * @return the value of t_housestars.described
     *
     * @mbg.generated Mon Nov 18 20:16:27 CST 2019
     */
    public Double getDescribed() {
        return described;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_housestars.described
     *
     * @param described the value for t_housestars.described
     *
     * @mbg.generated Mon Nov 18 20:16:27 CST 2019
     */
    public void setDescribed(Double described) {
        this.described = described;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_housestars.location
     *
     * @return the value of t_housestars.location
     *
     * @mbg.generated Mon Nov 18 20:16:27 CST 2019
     */
    public Double getLocation() {
        return location;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_housestars.location
     *
     * @param location the value for t_housestars.location
     *
     * @mbg.generated Mon Nov 18 20:16:27 CST 2019
     */
    public void setLocation(Double location) {
        this.location = location;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_housestars.communication
     *
     * @return the value of t_housestars.communication
     *
     * @mbg.generated Mon Nov 18 20:16:27 CST 2019
     */
    public Double getCommunication() {
        return communication;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_housestars.communication
     *
     * @param communication the value for t_housestars.communication
     *
     * @mbg.generated Mon Nov 18 20:16:27 CST 2019
     */
    public void setCommunication(Double communication) {
        this.communication = communication;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_housestars.occupancy
     *
     * @return the value of t_housestars.occupancy
     *
     * @mbg.generated Mon Nov 18 20:16:27 CST 2019
     */
    public Double getOccupancy() {
        return occupancy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_housestars.occupancy
     *
     * @param occupancy the value for t_housestars.occupancy
     *
     * @mbg.generated Mon Nov 18 20:16:27 CST 2019
     */
    public void setOccupancy(Double occupancy) {
        this.occupancy = occupancy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_housestars.clean
     *
     * @return the value of t_housestars.clean
     *
     * @mbg.generated Mon Nov 18 20:16:27 CST 2019
     */
    public Double getClean() {
        return clean;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_housestars.clean
     *
     * @param clean the value for t_housestars.clean
     *
     * @mbg.generated Mon Nov 18 20:16:27 CST 2019
     */
    public void setClean(Double clean) {
        this.clean = clean;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_housestars.costperformance
     *
     * @return the value of t_housestars.costperformance
     *
     * @mbg.generated Mon Nov 18 20:16:27 CST 2019
     */
    public Double getCostperformance() {
        return costperformance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_housestars.costperformance
     *
     * @param costperformance the value for t_housestars.costperformance
     *
     * @mbg.generated Mon Nov 18 20:16:27 CST 2019
     */
    public void setCostperformance(Double costperformance) {
        this.costperformance = costperformance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_housestars.createdate
     *
     * @return the value of t_housestars.createdate
     *
     * @mbg.generated Mon Nov 18 20:16:27 CST 2019
     */
    public Date getCreatedate() {
        return createdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_housestars.createdate
     *
     * @param createdate the value for t_housestars.createdate
     *
     * @mbg.generated Mon Nov 18 20:16:27 CST 2019
     */
    public void setCreatedate(Date createdate) {
        this.createdate = createdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_housestars.status
     *
     * @return the value of t_housestars.status
     *
     * @mbg.generated Mon Nov 18 20:16:27 CST 2019
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_housestars.status
     *
     * @param status the value for t_housestars.status
     *
     * @mbg.generated Mon Nov 18 20:16:27 CST 2019
     */
    public void setStatus(Integer status) {
        this.status = status;
    }
}