package com.shana.house.model;

import java.util.Date;

public class HouseRule {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_houserule.hrid
     *
     * @mbg.generated Mon Nov 18 20:16:27 CST 2019
     */
    private Integer hrid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_houserule.hid
     *
     * @mbg.generated Mon Nov 18 20:16:27 CST 2019
     */
    private Integer hid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_houserule.child
     *
     * @mbg.generated Mon Nov 18 20:16:27 CST 2019
     */
    private Integer child;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_houserule.baby
     *
     * @mbg.generated Mon Nov 18 20:16:27 CST 2019
     */
    private Integer baby;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_houserule.pets
     *
     * @mbg.generated Mon Nov 18 20:16:27 CST 2019
     */
    private Integer pets;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_houserule.smoking
     *
     * @mbg.generated Mon Nov 18 20:16:27 CST 2019
     */
    private Integer smoking;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_houserule.party
     *
     * @mbg.generated Mon Nov 18 20:16:27 CST 2019
     */
    private Integer party;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_houserule.others
     *
     * @mbg.generated Mon Nov 18 20:16:27 CST 2019
     */
    private Integer others;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_houserule.createdate
     *
     * @mbg.generated Mon Nov 18 20:16:27 CST 2019
     */
    private Date createdate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_houserule.status
     *
     * @mbg.generated Mon Nov 18 20:16:27 CST 2019
     */
    private Integer status;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_houserule.hrid
     *
     * @return the value of t_houserule.hrid
     *
     * @mbg.generated Mon Nov 18 20:16:27 CST 2019
     */
    public Integer getHrid() {
        return hrid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_houserule.hrid
     *
     * @param hrid the value for t_houserule.hrid
     *
     * @mbg.generated Mon Nov 18 20:16:27 CST 2019
     */
    public void setHrid(Integer hrid) {
        this.hrid = hrid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_houserule.hid
     *
     * @return the value of t_houserule.hid
     *
     * @mbg.generated Mon Nov 18 20:16:27 CST 2019
     */
    public Integer getHid() {
        return hid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_houserule.hid
     *
     * @param hid the value for t_houserule.hid
     *
     * @mbg.generated Mon Nov 18 20:16:27 CST 2019
     */
    public void setHid(Integer hid) {
        this.hid = hid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_houserule.child
     *
     * @return the value of t_houserule.child
     *
     * @mbg.generated Mon Nov 18 20:16:27 CST 2019
     */
    public Integer getChild() {
        return child;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_houserule.child
     *
     * @param child the value for t_houserule.child
     *
     * @mbg.generated Mon Nov 18 20:16:27 CST 2019
     */
    public void setChild(Integer child) {
        this.child = child;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_houserule.baby
     *
     * @return the value of t_houserule.baby
     *
     * @mbg.generated Mon Nov 18 20:16:27 CST 2019
     */
    public Integer getBaby() {
        return baby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_houserule.baby
     *
     * @param baby the value for t_houserule.baby
     *
     * @mbg.generated Mon Nov 18 20:16:27 CST 2019
     */
    public void setBaby(Integer baby) {
        this.baby = baby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_houserule.pets
     *
     * @return the value of t_houserule.pets
     *
     * @mbg.generated Mon Nov 18 20:16:27 CST 2019
     */
    public Integer getPets() {
        return pets;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_houserule.pets
     *
     * @param pets the value for t_houserule.pets
     *
     * @mbg.generated Mon Nov 18 20:16:27 CST 2019
     */
    public void setPets(Integer pets) {
        this.pets = pets;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_houserule.smoking
     *
     * @return the value of t_houserule.smoking
     *
     * @mbg.generated Mon Nov 18 20:16:27 CST 2019
     */
    public Integer getSmoking() {
        return smoking;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_houserule.smoking
     *
     * @param smoking the value for t_houserule.smoking
     *
     * @mbg.generated Mon Nov 18 20:16:27 CST 2019
     */
    public void setSmoking(Integer smoking) {
        this.smoking = smoking;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_houserule.party
     *
     * @return the value of t_houserule.party
     *
     * @mbg.generated Mon Nov 18 20:16:27 CST 2019
     */
    public Integer getParty() {
        return party;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_houserule.party
     *
     * @param party the value for t_houserule.party
     *
     * @mbg.generated Mon Nov 18 20:16:27 CST 2019
     */
    public void setParty(Integer party) {
        this.party = party;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_houserule.others
     *
     * @return the value of t_houserule.others
     *
     * @mbg.generated Mon Nov 18 20:16:27 CST 2019
     */
    public Integer getOthers() {
        return others;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_houserule.others
     *
     * @param others the value for t_houserule.others
     *
     * @mbg.generated Mon Nov 18 20:16:27 CST 2019
     */
    public void setOthers(Integer others) {
        this.others = others;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_houserule.createdate
     *
     * @return the value of t_houserule.createdate
     *
     * @mbg.generated Mon Nov 18 20:16:27 CST 2019
     */
    public Date getCreatedate() {
        return createdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_houserule.createdate
     *
     * @param createdate the value for t_houserule.createdate
     *
     * @mbg.generated Mon Nov 18 20:16:27 CST 2019
     */
    public void setCreatedate(Date createdate) {
        this.createdate = createdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_houserule.status
     *
     * @return the value of t_houserule.status
     *
     * @mbg.generated Mon Nov 18 20:16:27 CST 2019
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_houserule.status
     *
     * @param status the value for t_houserule.status
     *
     * @mbg.generated Mon Nov 18 20:16:27 CST 2019
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    @Override
    public String toString() {
        return "HouseRule{" +
                "hrid=" + hrid +
                ", hid=" + hid +
                ", child=" + child +
                ", baby=" + baby +
                ", pets=" + pets +
                ", smoking=" + smoking +
                ", party=" + party +
                ", others=" + others +
                ", createdate=" + createdate +
                ", status=" + status +
                '}';
    }
}