package com.shana.house.model;

import java.io.Serializable;
import java.util.Date;

public class House implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_house.hid
     *
     * @mbg.generated Mon Nov 18 20:16:27 CST 2019
     */
    private Integer hid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_house.uid
     *
     * @mbg.generated Mon Nov 18 20:16:27 CST 2019
     */
    private Integer uid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_house.hname
     *
     * @mbg.generated Mon Nov 18 20:16:27 CST 2019
     */
    private String hname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_house.location
     *
     * @mbg.generated Mon Nov 18 20:16:27 CST 2019
     */
    private String location;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_house.city
     *
     * @mbg.generated Mon Nov 18 20:16:27 CST 2019
     */
    private String city;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_house.housetype
     *
     * @mbg.generated Mon Nov 18 20:16:27 CST 2019
     */
    private Integer housetype;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_house.rentaltype
     *
     * @mbg.generated Mon Nov 18 20:16:27 CST 2019
     */
    private Integer rentaltype;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_house.img
     *
     * @mbg.generated Mon Nov 18 20:16:27 CST 2019
     */
    private String img;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_house.maxtenant
     *
     * @mbg.generated Mon Nov 18 20:16:27 CST 2019
     */
    private Integer maxtenant;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_house.bedroomnum
     *
     * @mbg.generated Mon Nov 18 20:16:27 CST 2019
     */
    private Integer bedroomnum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_house.bednum
     *
     * @mbg.generated Mon Nov 18 20:16:27 CST 2019
     */
    private Integer bednum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_house.bathroomnum
     *
     * @mbg.generated Mon Nov 18 20:16:27 CST 2019
     */
    private Double bathroomnum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_house.description
     *
     * @mbg.generated Mon Nov 18 20:16:27 CST 2019
     */
    private String description;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_house.startdate
     *
     * @mbg.generated Mon Nov 18 20:16:27 CST 2019
     */
    private Date startdate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_house.enddate
     *
     * @mbg.generated Mon Nov 18 20:16:27 CST 2019
     */
    private Date enddate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_house.price
     *
     * @mbg.generated Mon Nov 18 20:16:27 CST 2019
     */
    private Double price;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_house.seecount
     *
     * @mbg.generated Mon Nov 18 20:16:27 CST 2019
     */
    private Integer seecount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_house.createdate
     *
     * @mbg.generated Mon Nov 18 20:16:27 CST 2019
     */
    private Date createdate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_house.status
     *
     * @mbg.generated Mon Nov 18 20:16:27 CST 2019
     */
    private Integer status;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_house.hid
     *
     * @return the value of t_house.hid
     *
     * @mbg.generated Mon Nov 18 20:16:27 CST 2019
     */
    public Integer getHid() {
        return hid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_house.hid
     *
     * @param hid the value for t_house.hid
     *
     * @mbg.generated Mon Nov 18 20:16:27 CST 2019
     */
    public void setHid(Integer hid) {
        this.hid = hid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_house.uid
     *
     * @return the value of t_house.uid
     *
     * @mbg.generated Mon Nov 18 20:16:27 CST 2019
     */
    public Integer getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_house.uid
     *
     * @param uid the value for t_house.uid
     *
     * @mbg.generated Mon Nov 18 20:16:27 CST 2019
     */
    public void setUid(Integer uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_house.hname
     *
     * @return the value of t_house.hname
     *
     * @mbg.generated Mon Nov 18 20:16:27 CST 2019
     */
    public String getHname() {
        return hname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_house.hname
     *
     * @param hname the value for t_house.hname
     *
     * @mbg.generated Mon Nov 18 20:16:27 CST 2019
     */
    public void setHname(String hname) {
        this.hname = hname == null ? null : hname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_house.location
     *
     * @return the value of t_house.location
     *
     * @mbg.generated Mon Nov 18 20:16:27 CST 2019
     */
    public String getLocation() {
        return location;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_house.location
     *
     * @param location the value for t_house.location
     *
     * @mbg.generated Mon Nov 18 20:16:27 CST 2019
     */
    public void setLocation(String location) {
        this.location = location == null ? null : location.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_house.city
     *
     * @return the value of t_house.city
     *
     * @mbg.generated Mon Nov 18 20:16:27 CST 2019
     */
    public String getCity() {
        return city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_house.city
     *
     * @param city the value for t_house.city
     *
     * @mbg.generated Mon Nov 18 20:16:27 CST 2019
     */
    public void setCity(String city) {
        this.city = city == null ? null : city.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_house.housetype
     *
     * @return the value of t_house.housetype
     *
     * @mbg.generated Mon Nov 18 20:16:27 CST 2019
     */
    public Integer getHousetype() {
        return housetype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_house.housetype
     *
     * @param housetype the value for t_house.housetype
     *
     * @mbg.generated Mon Nov 18 20:16:27 CST 2019
     */
    public void setHousetype(Integer housetype) {
        this.housetype = housetype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_house.rentaltype
     *
     * @return the value of t_house.rentaltype
     *
     * @mbg.generated Mon Nov 18 20:16:27 CST 2019
     */
    public Integer getRentaltype() {
        return rentaltype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_house.rentaltype
     *
     * @param rentaltype the value for t_house.rentaltype
     *
     * @mbg.generated Mon Nov 18 20:16:27 CST 2019
     */
    public void setRentaltype(Integer rentaltype) {
        this.rentaltype = rentaltype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_house.img
     *
     * @return the value of t_house.img
     *
     * @mbg.generated Mon Nov 18 20:16:27 CST 2019
     */
    public String getImg() {
        return img;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_house.img
     *
     * @param img the value for t_house.img
     *
     * @mbg.generated Mon Nov 18 20:16:27 CST 2019
     */
    public void setImg(String img) {
        this.img = img == null ? null : img.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_house.maxtenant
     *
     * @return the value of t_house.maxtenant
     *
     * @mbg.generated Mon Nov 18 20:16:27 CST 2019
     */
    public Integer getMaxtenant() {
        return maxtenant;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_house.maxtenant
     *
     * @param maxtenant the value for t_house.maxtenant
     *
     * @mbg.generated Mon Nov 18 20:16:27 CST 2019
     */
    public void setMaxtenant(Integer maxtenant) {
        this.maxtenant = maxtenant;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_house.bedroomnum
     *
     * @return the value of t_house.bedroomnum
     *
     * @mbg.generated Mon Nov 18 20:16:27 CST 2019
     */
    public Integer getBedroomnum() {
        return bedroomnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_house.bedroomnum
     *
     * @param bedroomnum the value for t_house.bedroomnum
     *
     * @mbg.generated Mon Nov 18 20:16:27 CST 2019
     */
    public void setBedroomnum(Integer bedroomnum) {
        this.bedroomnum = bedroomnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_house.bednum
     *
     * @return the value of t_house.bednum
     *
     * @mbg.generated Mon Nov 18 20:16:27 CST 2019
     */
    public Integer getBednum() {
        return bednum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_house.bednum
     *
     * @param bednum the value for t_house.bednum
     *
     * @mbg.generated Mon Nov 18 20:16:27 CST 2019
     */
    public void setBednum(Integer bednum) {
        this.bednum = bednum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_house.bathroomnum
     *
     * @return the value of t_house.bathroomnum
     *
     * @mbg.generated Mon Nov 18 20:16:27 CST 2019
     */
    public Double getBathroomnum() {
        return bathroomnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_house.bathroomnum
     *
     * @param bathroomnum the value for t_house.bathroomnum
     *
     * @mbg.generated Mon Nov 18 20:16:27 CST 2019
     */
    public void setBathroomnum(Double bathroomnum) {
        this.bathroomnum = bathroomnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_house.description
     *
     * @return the value of t_house.description
     *
     * @mbg.generated Mon Nov 18 20:16:27 CST 2019
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_house.description
     *
     * @param description the value for t_house.description
     *
     * @mbg.generated Mon Nov 18 20:16:27 CST 2019
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_house.startdate
     *
     * @return the value of t_house.startdate
     *
     * @mbg.generated Mon Nov 18 20:16:27 CST 2019
     */
    public Date getStartdate() {
        return startdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_house.startdate
     *
     * @param startdate the value for t_house.startdate
     *
     * @mbg.generated Mon Nov 18 20:16:27 CST 2019
     */
    public void setStartdate(Date startdate) {
        this.startdate = startdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_house.enddate
     *
     * @return the value of t_house.enddate
     *
     * @mbg.generated Mon Nov 18 20:16:27 CST 2019
     */
    public Date getEnddate() {
        return enddate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_house.enddate
     *
     * @param enddate the value for t_house.enddate
     *
     * @mbg.generated Mon Nov 18 20:16:27 CST 2019
     */
    public void setEnddate(Date enddate) {
        this.enddate = enddate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_house.price
     *
     * @return the value of t_house.price
     *
     * @mbg.generated Mon Nov 18 20:16:27 CST 2019
     */
    public Double getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_house.price
     *
     * @param price the value for t_house.price
     *
     * @mbg.generated Mon Nov 18 20:16:27 CST 2019
     */
    public void setPrice(Double price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_house.seecount
     *
     * @return the value of t_house.seecount
     *
     * @mbg.generated Mon Nov 18 20:16:27 CST 2019
     */
    public Integer getSeecount() {
        return seecount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_house.seecount
     *
     * @param seecount the value for t_house.seecount
     *
     * @mbg.generated Mon Nov 18 20:16:27 CST 2019
     */
    public void setSeecount(Integer seecount) {
        this.seecount = seecount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_house.createdate
     *
     * @return the value of t_house.createdate
     *
     * @mbg.generated Mon Nov 18 20:16:27 CST 2019
     */
    public Date getCreatedate() {
        return createdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_house.createdate
     *
     * @param createdate the value for t_house.createdate
     *
     * @mbg.generated Mon Nov 18 20:16:27 CST 2019
     */
    public void setCreatedate(Date createdate) {
        this.createdate = createdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_house.status
     *
     * @return the value of t_house.status
     *
     * @mbg.generated Mon Nov 18 20:16:27 CST 2019
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_house.status
     *
     * @param status the value for t_house.status
     *
     * @mbg.generated Mon Nov 18 20:16:27 CST 2019
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    @Override
    public String toString() {
        return "House{" +
                "hid=" + hid +
                ", uid=" + uid +
                ", hname='" + hname + '\'' +
                ", location='" + location + '\'' +
                ", city='" + city + '\'' +
                ", housetype=" + housetype +
                ", rentaltype=" + rentaltype +
                ", img='" + img + '\'' +
                ", maxtenant=" + maxtenant +
                ", bedroomnum=" + bedroomnum +
                ", bednum=" + bednum +
                ", bathroomnum=" + bathroomnum +
                ", description='" + description + '\'' +
                ", startdate=" + startdate +
                ", enddate=" + enddate +
                ", price=" + price +
                ", seecount=" + seecount +
                ", createdate=" + createdate +
                ", status=" + status +
                '}';
    }
}