package com.shana.house.model;

import java.util.Date;

public class Orders {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_orders.oid
     *
     * @mbg.generated Mon Nov 18 20:16:27 CST 2019
     */
    private Integer oid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_orders.uid
     *
     * @mbg.generated Mon Nov 18 20:16:27 CST 2019
     */
    private Integer uid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_orders.hid
     *
     * @mbg.generated Mon Nov 18 20:16:27 CST 2019
     */
    private Integer hid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_orders.startdate
     *
     * @mbg.generated Mon Nov 18 20:16:27 CST 2019
     */
    private Date startdate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_orders.enddate
     *
     * @mbg.generated Mon Nov 18 20:16:27 CST 2019
     */
    private Date enddate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_orders.price
     *
     * @mbg.generated Mon Nov 18 20:16:27 CST 2019
     */
    private Double price;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_orders.totalprice
     *
     * @mbg.generated Mon Nov 18 20:16:27 CST 2019
     */
    private Double totalprice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_orders.totalday
     *
     * @mbg.generated Mon Nov 18 20:16:27 CST 2019
     */
    private Integer totalday;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_orders.peoplenum
     *
     * @mbg.generated Mon Nov 18 20:16:27 CST 2019
     */
    private Integer peoplenum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_orders.createdate
     *
     * @mbg.generated Mon Nov 18 20:16:27 CST 2019
     */
    private Date createdate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_orders.status
     *
     * @mbg.generated Mon Nov 18 20:16:27 CST 2019
     */
    private Integer status;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_orders.oid
     *
     * @return the value of t_orders.oid
     *
     * @mbg.generated Mon Nov 18 20:16:27 CST 2019
     */
    public Integer getOid() {
        return oid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_orders.oid
     *
     * @param oid the value for t_orders.oid
     *
     * @mbg.generated Mon Nov 18 20:16:27 CST 2019
     */
    public void setOid(Integer oid) {
        this.oid = oid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_orders.uid
     *
     * @return the value of t_orders.uid
     *
     * @mbg.generated Mon Nov 18 20:16:27 CST 2019
     */
    public Integer getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_orders.uid
     *
     * @param uid the value for t_orders.uid
     *
     * @mbg.generated Mon Nov 18 20:16:27 CST 2019
     */
    public void setUid(Integer uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_orders.hid
     *
     * @return the value of t_orders.hid
     *
     * @mbg.generated Mon Nov 18 20:16:27 CST 2019
     */
    public Integer getHid() {
        return hid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_orders.hid
     *
     * @param hid the value for t_orders.hid
     *
     * @mbg.generated Mon Nov 18 20:16:27 CST 2019
     */
    public void setHid(Integer hid) {
        this.hid = hid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_orders.startdate
     *
     * @return the value of t_orders.startdate
     *
     * @mbg.generated Mon Nov 18 20:16:27 CST 2019
     */
    public Date getStartdate() {
        return startdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_orders.startdate
     *
     * @param startdate the value for t_orders.startdate
     *
     * @mbg.generated Mon Nov 18 20:16:27 CST 2019
     */
    public void setStartdate(Date startdate) {
        this.startdate = startdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_orders.enddate
     *
     * @return the value of t_orders.enddate
     *
     * @mbg.generated Mon Nov 18 20:16:27 CST 2019
     */
    public Date getEnddate() {
        return enddate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_orders.enddate
     *
     * @param enddate the value for t_orders.enddate
     *
     * @mbg.generated Mon Nov 18 20:16:27 CST 2019
     */
    public void setEnddate(Date enddate) {
        this.enddate = enddate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_orders.price
     *
     * @return the value of t_orders.price
     *
     * @mbg.generated Mon Nov 18 20:16:27 CST 2019
     */
    public Double getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_orders.price
     *
     * @param price the value for t_orders.price
     *
     * @mbg.generated Mon Nov 18 20:16:27 CST 2019
     */
    public void setPrice(Double price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_orders.totalprice
     *
     * @return the value of t_orders.totalprice
     *
     * @mbg.generated Mon Nov 18 20:16:27 CST 2019
     */
    public Double getTotalprice() {
        return totalprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_orders.totalprice
     *
     * @param totalprice the value for t_orders.totalprice
     *
     * @mbg.generated Mon Nov 18 20:16:27 CST 2019
     */
    public void setTotalprice(Double totalprice) {
        this.totalprice = totalprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_orders.totalday
     *
     * @return the value of t_orders.totalday
     *
     * @mbg.generated Mon Nov 18 20:16:27 CST 2019
     */
    public Integer getTotalday() {
        return totalday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_orders.totalday
     *
     * @param totalday the value for t_orders.totalday
     *
     * @mbg.generated Mon Nov 18 20:16:27 CST 2019
     */
    public void setTotalday(Integer totalday) {
        this.totalday = totalday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_orders.peoplenum
     *
     * @return the value of t_orders.peoplenum
     *
     * @mbg.generated Mon Nov 18 20:16:27 CST 2019
     */
    public Integer getPeoplenum() {
        return peoplenum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_orders.peoplenum
     *
     * @param peoplenum the value for t_orders.peoplenum
     *
     * @mbg.generated Mon Nov 18 20:16:27 CST 2019
     */
    public void setPeoplenum(Integer peoplenum) {
        this.peoplenum = peoplenum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_orders.createdate
     *
     * @return the value of t_orders.createdate
     *
     * @mbg.generated Mon Nov 18 20:16:27 CST 2019
     */
    public Date getCreatedate() {
        return createdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_orders.createdate
     *
     * @param createdate the value for t_orders.createdate
     *
     * @mbg.generated Mon Nov 18 20:16:27 CST 2019
     */
    public void setCreatedate(Date createdate) {
        this.createdate = createdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_orders.status
     *
     * @return the value of t_orders.status
     *
     * @mbg.generated Mon Nov 18 20:16:27 CST 2019
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_orders.status
     *
     * @param status the value for t_orders.status
     *
     * @mbg.generated Mon Nov 18 20:16:27 CST 2019
     */
    public void setStatus(Integer status) {
        this.status = status;
    }
}